# Dependencies
markdown:         kramdown
highlighter:      pygments


# Setup
title:            C.O. Scholl
tagline:          'Front end dev and games'
description:      'Currently in development'  
url:              http://COScholl.github.io/
baseurl:          /

author:
  name:           'Mark Otto & Chris Scholl'
  url:            http://COScholl.github.io

# Collections
collections_dir: collections
collections:
  grimoire:
    output: true
    permalink: /grimoire/:path/
  rpgs:
    output: true
    permalink: /rpgs/:path/


# PermaLinks not supported anymore
gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          "Fifth Edition"

github: [metadata] 
