# Dependencies
markdown:         kramdown
highlighter:      pygments


# Setup
title:            Title of Page
tagline:          'Something Witty About Page'
description:      'A more in depth description about the page'
url:              http://COScholl.github.io
baseurl:          

author:
  name:           'Mark Otto & Chris Scholl'
  url:            http://COScholl.github.io

# PermaLinks not supported anymore
gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          "Fifth Edition"

github: [metadata] 
