# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Title of Page
tagline:          'Something Witty About Page'
description:      'A more in depth description about the page'
url:              http://COScholl.github.io
baseurl:          /

author:
  name:           'Mark Otto & Chris Scholl'
  url:            http://COScholl.github.io

paginate:         5

# Custom vars
version:          "Fifth Edition"

github:
  repo:           https://github.com/poole/hyde
